In [2]:
import pandas as pd
pd.options.display.max_rows = 6000

calendar = pd.read_csv('calendar.csv')
listings = pd.read_csv('listings.csv')
reviews = pd.read_csv('reviews.csv')
neighborhoods = pd.read_csv('neighbourhoods.csv')
neighborhoods_geo = pd.read_json('neighbourhoods.geojson')

In [3]:
# calendar columns

print(calendar.columns)
print(calendar.dtypes)

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='object')
listing_id         int64
date              object
available         object
price             object
adjusted_price    object
minimum_nights     int64
maximum_nights     int64
dtype: object

In [4]:
calendar.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,31380,2019-07-10,f,$75.00,$75.00,3,1125
1,18666,2019-07-10,f,$130.00,$130.00,3,730
2,18666,2019-07-11,f,$130.00,$130.00,3,730
3,18666,2019-07-12,f,$130.00,$130.00,3,730
4,18666,2019-07-13,f,$130.00,$130.00,3,730

In [5]:
calendar.min()

listing_id             18666
date              2019-07-10
available                  f
minimum_nights             1
maximum_nights             1
dtype: object

In [6]:
calendar.max()

listing_id          36582760
date              2020-07-10
available                  t
minimum_nights           900
maximum_nights    2147483647
dtype: object

In [7]:
# listings columns

for i in listings.columns:
    print(i)
print(listings.dtypes)

id
listing_url
scrape_id
last_scraped
name
summary
space
description
experiences_offered
neighborhood_overview
notes
transit
access
interaction
house_rules
thumbnail_url
medium_url
picture_url
xl_picture_url
host_id
host_url
host_name
host_since
host_location
host_about
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_thumbnail_url
host_picture_url
host_neighbourhood
host_listings_count
host_total_listings_count
host_verifications
host_has_profile_pic
host_identity_verified
street
neighbourhood
neighbourhood_cleansed
neighbourhood_group_cleansed
city
state
zipcode
market
smart_location
country_code
country
latitude
longitude
is_location_exact
property_type
room_type
accommodates
bathrooms
bedrooms
beds
bed_type
amenities
square_feet
price
weekly_price
monthly_price
security_deposit
cleaning_fee
guests_included
extra_people
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_nights_avg_ntm
maximum_nights_avg_ntm
calendar_updated
has_availability
availability_30
availability_60
availability_90
availability_365
calendar_last_scraped
number_of_reviews
number_of_reviews_ltm
first_review
last_review
review_scores_rating
review_scores_accuracy
review_scores_cleanliness
review_scores_checkin
review_scores_communication
review_scores_location
review_scores_value
requires_license
license
jurisdiction_names
instant_bookable
is_business_travel_ready
cancellation_policy
require_guest_profile_picture
require_guest_phone_verification
calculated_host_listings_count
calculated_host_listings_count_entire_homes
calculated_host_listings_count_private_rooms
calculated_host_listings_count_shared_rooms
reviews_per_month
id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
name                                             object
summary                                          object
space                                            object
description                                      object
experiences_offered                              object
neighborhood_overview                            object
notes                                            object
transit                                          object
access                                           object
interaction                                      object
house_rules                                      object
thumbnail_url                                   float64
medium_url                                      float64
picture_url                                      object
xl_picture_url                                  float64
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                            float64
host_is_superhost                                object
host_thumbnail_url                               object
host_picture_url                                 object
host_neighbourhood                               object
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                               object
host_has_profile_pic                             object
host_identity_verified                           object
street                                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
neighbourhood_group_cleansed                     object
city                                             object
state                                            object
zipcode                                          object
market                                           object
smart_location                                   object
country_code                                     object
country                                          object
latitude                                        float64
longitude                                       float64
is_location_exact                                object
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bedrooms                                        float64
beds                                            float64
bed_type                                         object
amenities                                        object
square_feet                                     float64
price                                            object
weekly_price                                     object
monthly_price                                    object
security_deposit                                 object
cleaning_fee                                     object
guests_included                                   int64
extra_people                                     object
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                            int64
maximum_minimum_nights                            int64
minimum_maximum_nights                            int64
maximum_maximum_nights                            int64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                 object
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                 object
license                                          object
jurisdiction_names                              float64
instant_bookable                                 object
is_business_travel_ready                         object
cancellation_policy                              object
require_guest_profile_picture                    object
require_guest_phone_verification                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
dtype: object

In [8]:
listings['amenities']

0        {TV,Internet,Wifi,"Air conditioning","Wheelcha...
1        {TV,Internet,Wifi,"Air conditioning","Wheelcha...
2        {TV,Wifi,Kitchen,"Paid parking off premises",E...
3        {TV,Internet,Wifi,"Wheelchair accessible",Kitc...
4        {TV,Wifi,"Air conditioning",Kitchen,"Smoking a...
                               ...
19828    {TV,Wifi,Kitchen,Elevator,Heating,Washer,Dryer...
19829    {Wifi,Kitchen,"Free parking on premises",Heati...
19830    {Wifi,Kitchen,"Smoking allowed","Pets allowed"...
19831    {TV,Wifi,"Air conditioning",Kitchen,Elevator,H...
19832    {TV,Wifi,Kitchen,Elevator,Washer,Essentials,Ha...
Name: amenities, Length: 19833, dtype: object

In [9]:
listings.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,18666,https://www.airbnb.com/rooms/18666,20190710134514,2019-07-10,Flat with Sunny Terrace,"Apartment located near the ""Plaza de las Glori...",Nice apartment situated on the penthouse floor...,"Apartment located near the ""Plaza de las Glori...",none,Apartment in Barcelona near to the Plaza de la...,...,f,f,flexible,f,f,31,31,0,0,0.02
1,18674,https://www.airbnb.com/rooms/18674,20190710134514,2019-07-10,Huge flat for 8 people close to Sagrada Familia,110m2 apartment to rent in Barcelona. Located ...,Apartment with 110 m2 located in the 6th floor...,110m2 apartment to rent in Barcelona. Located ...,none,Apartment in Barcelona located in the heart of...,...,t,f,strict_14_with_grace_period,f,f,31,31,0,0,0.20
2,21605,https://www.airbnb.com/rooms/21605,20190710134514,2019-07-10,Nice and sunny duble room,"The flat is in Poblenou district, and the room...","L'apartament està al barri de Poblenou, i l'ha...","The flat is in Poblenou district, and the room...",none,Poblenou as one of the few areas that has grow...,...,f,f,moderate,f,f,2,0,2,0,3.08
3,23197,https://www.airbnb.com/rooms/23197,20190710134514,2019-07-10,FORUM DELUXE 5 MINS WALK CCIB CENTER & SEA!,I do not accept groups of young people under 2...,Elegant spacious apartment suitable for 6. Amp...,I do not accept groups of young people under 2...,none,Strategically located in the area of Parc del ...,...,t,f,strict_14_with_grace_period,f,t,2,2,0,0,0.44
4,25786,https://www.airbnb.com/rooms/25786,20190710134514,2019-07-10,NICE ROOM AVAILABLE IN THE HEART OF GRACIA,JUST GO THROUGH THE MANY REVIEWS I GOT THROUGH...,Room available for rent.- PEDRO PEREZ. Share...,JUST GO THROUGH THE MANY REVIEWS I GOT THROUGH...,none,Solo decir que a menudo ni salgo del barrio. M...,...,t,f,strict_14_with_grace_period,t,t,1,0,1,0,2.22

In [10]:
# reviews columns

print(reviews.columns)
print(reviews.dtypes)

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')
listing_id        int64
id                int64
date             object
reviewer_id       int64
reviewer_name    object
comments         object
dtype: object

In [11]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,18666,50158511,2015-10-10,1559265,Jody,Very nice flat. We had easy transportation to ...
1,18674,4808211,2013-05-27,4841196,Caron,"Great location. Clean, spacious flat. Would re..."
2,18674,10660311,2014-03-02,11600277,Juan Carlos,Mi mejor recomendación para este departamento....
3,18674,41087522,2015-08-04,35231385,Shlomi,"Big apartment, well equipped.\r\nVery good ser..."
4,18674,81000756,2016-06-20,23223644,Joost,The Check in was fast and flexible. The price ...

In [12]:
# neighborhoods columns

print(neighborhoods.columns)
print(neighborhoods.dtypes)

Index(['neighbourhood_group', 'neighbourhood'], dtype='object')
neighbourhood_group    object
neighbourhood          object
dtype: object

In [13]:
neighborhoods.head()

  neighbourhood_group                          neighbourhood
0        Ciutat Vella                         el Barri Gòtic
1        Ciutat Vella                               el Raval
2        Ciutat Vella                         la Barceloneta
3        Ciutat Vella  Sant Pere, Santa Caterina i la Ribera
4            Eixample                          el Fort Pienc

In [14]:
# neighborhoods geo columns

print(neighborhoods_geo.columns)
print(neighborhoods_geo.dtypes)

Index(['type', 'features'], dtype='object')
type        object
features    object
dtype: object

In [15]:
neighborhoods_geo.head()

                type                                           features
0  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Mult...
1  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Mult...
2  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Mult...
3  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Mult...
4  FeatureCollection  {'type': 'Feature', 'geometry': {'type': 'Mult...

In [16]:
for i in neighborhoods_geo.columns:
    print(i)

type
features

In [20]:
neighborhoods_geo['features'][0]

{'type': 'Feature',
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[2.177386, 41.375347],
     [2.178532, 41.374845],
     [2.178881, 41.374692],
     [2.178217, 41.373863],
     [2.183148, 41.371629],
     [2.182094, 41.37031],
     [2.177653, 41.372329],
     [2.177632, 41.372392],
     [2.176918, 41.372711],
     [2.176856, 41.372748],
     [2.176858, 41.372849],
     [2.17641, 41.373055],
     [2.175677, 41.373392],
     [2.175622, 41.373422],
     [2.176401, 41.374378],
     [2.1752029999999998, 41.374681],
     [2.17323, 41.374827],
     [2.172748, 41.37486],
     [2.172725, 41.374862],
     [2.171917, 41.374922],
     [2.170069, 41.375048],
     [2.169626, 41.375033],
     [2.168574, 41.374982],
     [2.167865, 41.375016],
     [2.167649, 41.375211],
     [2.167455, 41.375404],
     [2.166552, 41.376081],
     [2.166114, 41.376431],
     [2.1660909999999998, 41.376448],
     [2.165474, 41.376941],
     [2.164687, 41.377567],
     [2.164681, 41.377572],
     [2.164358, 41.37781],
     [2.16325, 41.378681],
     [2.163127, 41.378774],
     [2.163358, 41.380369],
     [2.163357, 41.380467],
     [2.163494, 41.381382],
     [2.163538, 41.381701],
     [2.1636, 41.382151],
     [2.163631, 41.38238],
     [2.163639, 41.38243],
     [2.163887, 41.384163],
     [2.163899, 41.384248],
     [2.1640449999999998, 41.38528],
     [2.1640639999999998, 41.385433],
     [2.164865, 41.385948],
     [2.170061, 41.385501],
     [2.170664, 41.384614],
     [2.171716, 41.383066],
     [2.17174, 41.383031],
     [2.172097, 41.382505],
     [2.173171, 41.381299],
     [2.173297, 41.381157],
     [2.174088, 41.380269],
     [2.174174, 41.380172],
     [2.17472, 41.37954],
     [2.175121, 41.379077],
     [2.175452, 41.378802],
     [2.1755430000000002, 41.378677],
     [2.175769, 41.378298],
     [2.175792, 41.378258],
     [2.176022, 41.377862],
     [2.176877, 41.376744],
     [2.177548, 41.376018],
     [2.177478, 41.375937],
     [2.177448, 41.375886],
     [2.17744, 41.375868],
     [2.17743, 41.375842],
     [2.177423, 41.375816],
     [2.177418, 41.37579],
     [2.177415, 41.375764],
     [2.177414, 41.37575],
     [2.177413, 41.375735],
     [2.177414, 41.375719],
     [2.177417, 41.375703],
     [2.17742, 41.375688],
     [2.177425, 41.375673],
     [2.177432, 41.375658],
     [2.177439, 41.375643],
     [2.177447, 41.375629],
     [2.177458, 41.375613],
     [2.17747, 41.375601],
     [2.177481, 41.37559],
     [2.177493, 41.375579],
     [2.177507, 41.375569],
     [2.177546, 41.375544],
     [2.177386, 41.375347]]]]},
 'properties': {'neighbourhood': 'el Raval',
  'neighbourhood_group': 'Ciutat Vella'}}